version: '3.3'

#env_file: .env

services:
  db:
    image: postgres_pgtap:alpine
    restart: always
    container_name: dev_db
    ports:
      - 6543:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=${PGPASS}
      # - POSTGRES_INITDB_ARGS="-A md5"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
# volumes:
#   maildata:
#     driver: local
#   mailstate:
#     driver: local
